### ISSUE TITLE
Leaks file descriptors on Windows

### ISSUE THREAD

**Issue by georgthegreat** [torakiki/pdfsam#215]
After merging certain number of small pdf-files (lets say 40 and more) and cleaning up merge panel, files often remain open (and therefore can't be removed from device).

![2017-02-19_10-26-29](https://cloud.githubusercontent.com/assets/1121500/23100273/f81a6dc2-f68d-11e6-8616-016239277763.png)

Closing PDFSam helps.

**Comment by torakiki** [comment]
This is related to https://bugs.openjdk.java.net/browse/JDK-4724038 and it seems it will be fixed in Java 10.
Some work has been done around this topic https://bugs.openjdk.java.net/browse/JDK-8148117 and I'm going to bring in some workaround/fix implemented by smart developers here 
https://git-wip-us.apache.org/repos/asf?p=lucene-solr.git;a=commit;h=7e03427 and https://github.com/netty/netty/blob/67be7c5b9f5920d5f99d40e8b483df112e103ba8/common/src/main/java/io/netty/util/internal/Cleaner0.java

related:

https://issues.apache.org/jira/browse/LUCENE-6989
https://github.com/netty/netty/issues/4756

**Comment by torakiki** [comment]
this was fixed here https://github.com/torakiki/sejda-io/issues/5
