### ISSUE TITLE
Feature REQ

### ISSUE THREAD

**Issue by ezekielar** [torakiki/pdfsam#222]
Thanks for this great and rare program!

_I use the Basic program for fast merging of PDF files._

- [x] - Adding the Settings icon to Menu
- [x] - Folder Add option for all of files within a folder.
- [ ] - Previous Merge settings with drop down should be saved (remembered) upon exit.
- [x] - Adding auto file name assignment to the Destination file
- [x] - Unchecked Compress output file(s) as default
- [x] - Open the completed file just after a job is finished successfully (Run > Completed) should be added as an option.

Normalise should be **Normalize**.

**Comment by AlisterH** [comment]
> Normalise should be Normalize

Not if you're English!

**Comment by DJCrashdummy** [comment]
number 3 (*"Previous ... settings ... should be saved (remembered) upon exit."*) is true for all functions of PDFsam! - it is pretty tedious to always remember and apply your preferred settings.

**Comment by torakiki** [comment]
@DJCrashdummy we do have a workspace save/load and load on startup, that should pretty much cover the case, doesn't it?

**Comment by DJCrashdummy** [comment]
@torakiki sorry for the late reply, i was very busy at work.

to be honest: i have overlooked this setting also because i hardly understood it (perhaps also some kind of lost in translation)... but i still can't verify nor deny it, because i don't know how to create such a `.json`-file nor do i find an example or some documentation about it! :frowning_face:
