### ISSUE TITLE
Sign with SHA256 / sign all files

### ISSUE THREAD

**Issue by alexhass** [torakiki/pdfsam#333]
MSI signature is currently SHA1.

Microsoft is phasing out SHA1 digital signatures because of its weakness. Please only sign with SHA-2 in future. https://support.microsoft.com/en-us/help/4472027/2019-sha-2-code-signing-support-requirement-for-windows-and-wsus

Signing all other PDFsam files would also be great as virus scanners typically whitelist signed applications / the signers.

**Comment by alexhass** [comment]
```
>jarsigner -verify javafx-base-11.0.1.jar

jar is unsigned.

>jarsigner -verify pdfsam-core-4.0.0.jar

jar is unsigned.
```

**Comment by torakiki** [comment]
I updated the script to sign the MSI using sha256. We also already sign all the bundles in the [release](https://github.com/torakiki/pdfsam/releases), you can find the .asc file corresponding to each package and verify the packages integrity using something like `gpg -vv --verify pdfsam-4.0.0-windows.zip.asc`, it produces and output like:
```
gpg: using character set 'utf-8'
gpg: armor: BEGIN PGP SIGNATURE
# off=0 ctb=89 tag=2 hlen=3 plen=563
:signature packet: algo 1, keyid BF019D784ED7F785
	version 4, created 1545400075, md5len 0, sigclass 0x00
	digest algo 10, begin of digest ae 66
	hashed subpkt 33 len 21 (issuer fpr v4 3E2455BB66A07C8E5547BB2ABF019D784ED7F785)
	hashed subpkt 2 len 4 (sig created 2018-12-21)
	subpkt 16 len 8 (issuer key ID BF019D784ED7F785)
	data: [4096 bits]
gpg: assuming signed data in 'pdfsam-4.0.0-windows.zip'
gpg: Signature made ven 21 dic 2018 14:47:55 CET
gpg:                using RSA key 3E2455BB66A07C8E5547BB2ABF019D784ED7F785
gpg: using pgp trust model
gpg: key 5370ADE93D0B9A0A: accepted as trusted key
gpg: key A1ED15340F055A49: accepted as trusted key
gpg: key A1632A944A24296C: accepted as trusted key
gpg: key BF019D784ED7F785: accepted as trusted key
gpg: Good signature from "Sober Lemur S.a.s. <info@pdfsam.org>" [ultimate]
gpg: binary signature, digest algorithm SHA512, key algorithm rsa4096
```
and you can then search for the id with `gpg --search-key BF019D784ED7F785` which should find this [key](http://keyserver.ubuntu.com:11371/pks/lookup?op=vindex&search=0xBF019D784ED7F785)

I don't sign jars because I already sign the packages and I don't see much value in signing the single jars but I'm open to discussion.. what's your use case?

**Comment by alexhass** [comment]
Great.

MSI and EXE / DLL signing is fine. In past year I had a lot of issues with virus scanner heuristic detection issues trying to detect crypto trojans. This caused destroyed applications or blocked Applications from running. 

Whitelisting the signer with the virus scanner vendor (e.g. trend micro) was always easy when the files have been signed.

I‘m not sure about the value of .jar signing. I only remembered that Oracle forced to sign every jar that runs with webstart; if I‘m not wrong. Maybe not needed here, but I suspect virus scanners trust applications with embedded digital signatures much more.
