### ISSUE TITLE
update folder location

### ISSUE THREAD

**Issue by hkperera** [torakiki/pdfsam#340]
once you have a workspace made, if one of the files in your list moves or you change the location. pdsam recognizes that the file is no longer in it's previous home, but there is no way of updating the location. the only option is to delete the current file and bring in the new one. This can by arduous  if there are multiple files.

**Comment by torakiki** [comment]
Workspaces are json text files, they can be opened with a standard text editor like Notepad++ and the location can be manually updated. I'm not sure this is something that should be handled by PDFsam and it feels like a corner case that's not worth investing in.... the workspace contains file paths, if you move the files PDFsam cannot find them anymore, what would be the expected behavior?
