### ISSUE TITLE
.exe installer on website contains malware

### ISSUE THREAD

**Issue by choglan** [torakiki/pdfsam#409]
Hello pdfsam,

I downloaded the .exe installer off of your website at https://pdfsam.org/download-pdfsam-basic/
I ran the installer through VirusTotal to check if it was safe, and it came back positive for [malware and a trojan.](https://www.virustotal.com/gui/file/e7d45216985f78b4c596c52f3e409f2d46662311474603d42ec2b12bfe9f04d4/detection)

Whoever is in control of the website should fix this immediately. I've used and recommended this program many times in the past, and it's completely unacceptable that an open-source project like this one should be responsible for infecting computers with malware. I've loved using this software in the past, and I was even about to donate to this project, but I'm going to use a different program after this.

**Comment by torakiki** [comment]
The windows **downloader** has 2 red flags on VirusTotal (out of 72 different antivirus software). It's flagged as a PuP, a potentially unwanted program, because it offers to try our premium product. That is clearly stated in the download page (in bold and with an image). We also offer MSI **installer** without any offer to try the premium product and we also offer the portable zip bundle.
PDFsam Basic is open source and the project includes sources to create the MSI, you can download the sources, compile the software and create the MSI yourself if you have any doubt about our installer.
