### ISSUE TITLE
Keyboard shortcuts (Clear, Remove, ...) are active when entering free text

### ISSUE THREAD

**Issue by aureole82** [torakiki/pdfsam#424]
1. Open Merge tool.
2. Add some PDF files.
3. Use the [Alt] key, e.g. for window switch [Alt]+[Tab].
4. Focus Destination file text box and try to enter "r" or "c".

Expacted behavior: The letters "r" or "c" are entered.
Actual behavior: The selected or all PDF files are removed.

**Comment by torakiki** [comment]
We have been reported this issue few times but we couldn't reproduce. What OS are you using? does it happen consistently?

**Comment by aureole82** [comment]
I found the difference and extended the description. It looks like you enable/disable shortcuts by a complete the [Alt] key down/up pressing. Shouldn't it be like the following?
* [Alt] key down: Enable keyboard shortcuts.
* [Alt] key up: Disable keyboard shortcuts.

Here's my sytem:
* Windows 10 Version 2004
* Portable Version of pdfsam:
  * PDF Split and Merge Basic Edition 4.1.4
  * OpenJDK Runtime Environment 11.0.8+10
  * Vendor: AdoptOpenJDK
  * Java runtime path: C:\Users\xxx\Downloads\pdfsam-4.1.4-windows\runtime
  * JavaFX runtime version 14.0.2+1
  * Max memory 3 GB

**Comment by torakiki** [comment]
Ok got it.. I've been able to reproduce it with the ALT+TAB
The expected behavior is that ALT+KEY triggers a feature, like ALT+a triggers a ADD (you can see the underlying letter on the toolbar buttons if you press the ALT key), these are called mnemonic. When you release the ALT key the mnemonic should be untriggered (the underline disappear). What happens with ALT+TAB is that somehow the mnemonic stays engaged ... not sure why, I've to dig a bit deeper but at least I can reproduce it now.

**Comment by torakiki** [comment]
This is the issue already opened in JavaFX https://bugs.openjdk.java.net/browse/JDK-8238731 but it's low priority and I wouldn't hold my breath on that. I'll see if there is a workaround.
