### ISSUE TITLE
Critical list column sorting bugs when dropping files

### ISSUE THREAD

**Issue by trexoftsys** [torakiki/pdfsam#440]
Hi - I'm a heavy user of this app, but it's hard to use it because of a really **annoying list sorting bug** not respecting the column sorting order when dragging & dropping _(this is one of the most basic functionality expected by users for a column-based list)_. Below I'm describing the scenarios that lead to this bug, along with GIF recordings:

1. **Sorting does Not work when the numbers are Not at the beginning of the filename**

> When dropping files that have numbers not at the beginning, for example, a file ending with "10" gets added after the file ending with "1" instead of the 9th file _(no matter if I set the name column to ascending order it just doesn't work)_:

![1](https://user-images.githubusercontent.com/71434536/104823638-49960e00-5854-11eb-9dda-a127a25b86b8.gif)

> More so, why are there **no "Move to Bottom" and "Move to Top" buttons**? If I have hundreds of files, I'm forced to move them one by one, which is impossible.

2. **Dropping files does Not automatically sort them if a column was set to a specific sorting order beforehand**

> When the list is empty and I set the column to automatically sort ascending, as soon as I drop the files *the list is Not automatically sorted* even though the column shows the sorted icon, but the sorting never happens:

![2](https://user-images.githubusercontent.com/71434536/104823744-1dc75800-5855-11eb-84b3-2e6455412bfd.gif)

> For a better example of this scenario, I tried setting the "Modified" column to sort ascending by date - as soon as I drop the files _(even if they are in the correct order in Explorer)_, **PDFSam will Not automatically sort them despite the column icon showing them as "sorted"**:

![3](https://user-images.githubusercontent.com/71434536/104823770-4a7b6f80-5855-11eb-864c-fdc5d1890bc9.gif)

As you can see in the above recording, the "Modified" column shows the ascending arrow icon, but the list is not sorted after dropping the files, _it's chaotic._

**Comment by tquentin** [comment]
Please let me comment on these problems.

> 1. Sorting does Not work when the numbers are Not at the beginning of the filename
If you know the logic on sorting, you should find that it takes many extra decision and coding to achieve the sorting you mentioned - 1, 2, 3 ... then 11, 12, 13, then 99, 100 .. etc as you are considering the numeric characters as a value instead of string , which it is not how sorting works in computer..
It does not matter if the number is at the beginning of the file or at the end..  

From sorting point of view in computer,
 1 > 100 > 2 > 3 > 310 > 4
 it is generic in all modern computer if they use ASCII code to store string (go back to basic computing 101).
 
 To make the sorting works, you need to rename your files (also plan ahead if you were creating a new collection and estimate the number of files you may have).  It just like if you estimated your business will have 1000 transactions daily and you will have YYMMDD as your invoice prefix, your invoice number format should be YYMMDD99999 (5 digits for the running number part at least).  otherwise once you made the 1000 transaction, it will have a invoice number overflow problem..
 
 
I agree with you on the "Move to Top" and "Move to Bottom" request.  It is a new request.  This implied PDFSAM is being used in heavy duty (as you mentioned) and this is a good request indeed.


> 2. Dropping files does Not automatically sort them if a column was set to a specific sorting order beforehand

Totally agree with you on this..  I just searched and found I did not raise this problem before but actually I know this problem a long time ago..  I'm glad you voiced this out for us.
 
 From a developer point of view, it has not triggered the sorting function after the add/remove function which it should have.

**Comment by trexoftsys** [comment]
>  (go back to basic computing 101).

I know how computers sort, but your app is used by humans who expect to see 10 being placed after 9, not after 1 😉 _(if the app would be used by computers, I'd have nothing to argument about the current alphabetical sorting that you're using)_

I know Java allows you to implement _custom sorters/comparators_ and there's an algorithm called __"natural sorting"__ out there that makes sorting look natural to humans by putting 10 after 9 just as humans would expect to see.

As mentioned on [this wikipage regarding natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order): _"Natural sort order has been promoted as being more human-friendly ("natural") than the machine-oriented pure alphabetical order."_

**Comment by torakiki** [comment]
Implemented point 2 in https://github.com/torakiki/pdfsam/commit/191e1c1b591cf5cc96c1d04fe6a0c144441c01de

**Comment by torakiki** [comment]
Regarding point 1
* `Move to top` and `Move to bottom` are available as context menu entry but at the moment work only with a single row selection, not sure why, I have to investigate.
* Natural sorting is already available if the digits are at the beginning of the file name, it needs to be enhanced to consider scenarios where the digits are at the end of the file name and also both, something like `123 filename 333.pdf`. I would say the goal is to behave as similar as possible to what file managers do, possibly the Windows file manager as it is the most used and probably what users would expect.

**Comment by trexoftsys** [comment]
Thank you so much for implementing point 2, that's the issue that gave me the most headaches! Can't wait for 4.2.2 to be released 👍 

As for natural sorting, it appears that Windows file manager indeed uses proper natural sorting and behaves just as humans would expect, so that would be a perfect goal.
