### ISSUE TITLE
VirusTotal flags Basic Installer as Malicious

### ISSUE THREAD

**Issue by luop90** [torakiki/pdfsam#466]
Title pretty much says all. The Windows installer for "Basic" downloaded from the website, is flagged by various anti-virus software on [VirusTotal](https://www.virustotal.com/gui/file/66b5c97f0fa9b3458696635caee235cc189c49094808bf3cfa84dd2166c1db66/detection). However, the main `pdfsam.exe` [comes up as clean](https://www.virustotal.com/gui/file/b315c3fcd66f907ce4631ffff210fa48af71d2c41ade61b6d399897feb10539b/detection).

Steps to reproduce:

1. Download the Windows installer for Basic
2. Upload to VirusTotal
3. See results

**Comment by torakiki** [comment]
Hi, please see here https://github.com/torakiki/pdfsam/issues/455
If you are talking about the .exe then we know, few AntiVirus flag it as PuP because it offers to try PDFsam Enhanced (even though we try to make it super clear and you can opt out). If you are talking about the MSI I have no idea why those two software are flagging it as PuP, there is no offer in the MSI and the scripts are open source.
