### ISSUE TITLE
Virustotal.com - pdfsam-4.2.9.msi - 1 security vendor and 1 sandbox flagged this file as malicious

### ISSUE THREAD

**Issue by alexeiroz** [torakiki/pdfsam#479]
pdfsam-4.2.9.msi - 1 security vendor and 1 sandbox flagged this file as malicious
https://www.virustotal.com/gui/file/b099fc354d6e4b6bafa92ab30c251a30dad445130b446b07aa9cd4908dc6692b
![image](https://user-images.githubusercontent.com/63920804/146373017-02f2250e-9057-441e-ae0b-88ed3af2f608.png)

**Comment by torakiki** [comment]
Hello,
we talked about it here https://github.com/torakiki/pdfsam/issues/455 and the MSI has a DrWeb antivirus flag of Potentially Unwanted Program because the .EXE downloader offers to try PDFsam Enhanced. The MSI shouldn't be flagged because there is no offer or anything in the MSI, just the PDFsam Basic program but they refuse to whitelist and answer, not sure why.
That said, I don't see or know those Crowdsourced Sigma Rules, is it something different from what I mentioned?
