### ISSUE TITLE
Please do not change the folder structure of your releases

### ISSUE THREAD

**Issue by onsamyj** [torakiki/pdfsam#530]
You are breaking dependencies.

To clarify, in version 4.3.4 it was `pdfsam-4.3.4-windows/pdfsam.exe`, now it is `pdfsam-5.0.1-windows/pdfsam/pdfsam.exe`.

Don’t go back now, but stay this way. Thank you!

**Comment by torakiki** [comment]
Hi,
why? What is the issue you have if the structure changes?

**Comment by onsamyj** [comment]
I am using [Scoop](https://scoop.sh/) which needs to know where the `.exe` file is located. Right now in a manifest file for **pdfsam** there is a rule `"extract_dir": "pdfsam-5.0.1-windows",`, which gives an error, because of this extra folder. We can change this rule, but if we have to change it for every new release, it kinda defeats the purpose of automatic updates :)

**Comment by torakiki** [comment]
Well, it's not for every release, this was a major release from 4 to 5 and a number of major things changed. We were using `launch4j` to generate the .exe but we moved to `jpackage`. This was done because `jpackage` is a standard jdk tool but mostly because we now run on jdk19 module path and `launch4j` doesn't support running the application from the module path (or at least I cound't figure it out from the documentation). The current structure is created by jpackage, see https://docs.oracle.com/en/java/javase/19/jpackage/packaging-overview.html and I don't know if it's possible to customize it. So I guess for this one time you will have to adjust the scripts but, unless anything major arise, I don't see the structure changing again in the near future.

**Comment by onsamyj** [comment]
That’s fine! Like I said, just don’t go back and forth :)

Thank you!
