### ISSUE TITLE
simple enhancements on save forms

### ISSUE THREAD

**Issue by jeffhawke** [torakiki/pdfsam#78]
In relation to the "Unisci" interface, while it's nice that the program suggests a default destination file in the same folder as the last added pdf, when you click on "sfoglia" to change it you are presented with an Explorer window pointed to the default folder (in my case, the Documents folder) instead of the file listed in the input field.

The same happens the first time I need to save the workspace (it points to the Documents folder) while it could be nice to have it point to the "Destination file" folder.

**Comment by torakiki** [comment]
I can't reproduce this. Implementation is already as you described so the FileChooser is pointed to the file/directory listed in the input field, and it's been like this since the beginning. I tested on Linux and Windows and got the desired behavior. Maybe I'm missing something but everything seems fine to me.
