### ISSUE TITLE
A short guide to compile PDFSam on Linux

### ISSUE THREAD

**Issue by Kalle72** [torakiki/pdfsam#96]
Hello,

Can you give me some hints to compile PdfSam 3 on Linux (I am on Gentoo and oracle-java 1.8 as well as apache-ant are installed). 

For PdfSam 2.2.4 everything was easy. Here one could do 
1) Extract all zip inside of the folder pdfsam-2.2.4e-out-src
2) In the folder "pdfsam-2.2.4e-out-src /pdfsam-maine/ant“ the file  „build.preferences“ is stored. One could reshape this file a little bit to
pdfsam.deploy.dir=../deploy									workspace.dir=../										
build.dir=../build
3) Run "ant" in "pdfsam-2.2.4e-out-src /pdfsam-maine/ant“
4) The program build up by this was now located in „pdfsam-2.2.4e-out-src/build/pdfsam-maine/release/dist/pdfsam-enhanced“

Is there an analogue way to build PdfSam 3 from source?

Thanks in advance and best Regards 
Kalle

**Comment by torakiki** [comment]
Simple steps are here https://github.com/torakiki/pdfsam/blob/master/pdfsam-docs/BUILDnRUN.md

We moved from Ant to Maven so once you have and once you have everything set up (jdk8, maven, gettext) it's just a matter of running `mvn clean install -Prelease`, this will create the package in the `target` directory. As things are currently still under development you first have to build Sejda because it's not released to maven central yet so in short, once you have jdk8 and maven running:
+ `git clone git@github.com:torakiki/sejda.git`
+ `git checkout 2.0.0-alpha6`
+ `mvn clean install`
+ `git clone git@github.com:torakiki/pdfsam.git`
+ `git checkout 3.0.0.M2`
+ `mvn clean install -Prelease`
If I'm not forgetting anything you should end up with the zip bundle in the `target` directory of the `pdfsam-community` module.
